### ISSUE TITLE
Problem when a loading model in test.py

### ISSUE THREAD

**Issue by jiwoongim** [chaofengc/Face-Sketch-Wild#3]
I think the issues below come from using old pytorch version. 
Pytorch 0.3.0 is not available and it is difficult to re-build from sources.
Do you have any latest version of face sketch code?

Thanks 

```(FaceSketch) [...@... Face-Sketch-Wild]$ CUDA_VISIBLE_DEVICES=0  python test.py 3
[0]
Traceback (most recent call last):
  File "face2sketch_wild.py", line 266, in <module>
    test(args)
  File "face2sketch_wild.py", line 222, in test
    Gnet.load_state_dict(torch.load(args.test_weight_path))
  File "/misc/vlgscratch4/ChoGroup/imj/miniconda3/envs/FaceSketch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
        Unexpected running stats buffer(s) "module.norm1.norm_func.running_mean" and "module.norm1.norm_func.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "module.norm2.norm_func.running_mean" and "module.norm2.norm_func.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "module.norm3.norm_func.running_mean" and "module.norm3.norm_func.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "module.res1.norm1.norm_func.running_mean" and "module.res1.norm1.norm_func.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "module.res1.norm2.norm_func.running_mean" and "module.res1.norm2.norm_func.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "module.res2.norm1.norm_func.running_mean" and "module.res2.norm1.norm_func.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "module.res2.norm2.norm_func.running_mean" and "module.res2.norm2.norm_func.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "module.res3.norm1.norm_func.running_mean" and "module.res3.norm1.norm_func.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "module.res3.norm2.norm_func.running_mean" and "module.res3.norm2.norm_func.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "module.res4.norm1.norm_func.running_mean" and "module.res4.norm1.norm_func.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "module.res4.norm2.norm_func.running_mean" and "module.res4.norm2.norm_func.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "module.res5.norm1.norm_func.running_mean" and "module.res5.norm1.norm_func.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "module.res5.norm2.norm_func.running_mean" and "module.res5.norm2.norm_func.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "module.norm4.norm_func.running_mean" and "module.norm4.norm_func.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "module.norm5.norm_func.running_mean" and "module.norm5.norm_func.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
(FaceSketch) [ji641@lion2 Face-Sketch-Wild]$ ```

**Comment by chaofengc** [comment]
Would you please try to set the `strict=False` in `load_state_dict` function ? Although the project is implemented by pytorch0.3, most are compatible with later version of pytorch.
